site_name: Interview Ready Vault
site_description: A comprehensive vault for Java, Spring, System Design, and DSA.

docs_dir: docs_link
site_dir: site

# Suppress the 2026 political warning in the terminal
extra:
  python_interrupt_on_signal: true

exclude_docs: |
  mkdocs.yml
  docs_link
  site
  run_local.sh
  extra.css
  overrides/*
  .github/*
  .git/*
  LICENSE
  Sample/*

theme:
  name: material
  # This helps clean up the UI for nested folders
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides

# This handles the relative links better
use_directory_urls: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list