site_name: Interview Ready Vault
site_description: A comprehensive vault for Java, Spring, System Design, and DSA.

docs_dir: .

# Prevents system files from appearing in your menu
exclude_docs:
  - mkdocs.yml
  - ".github/*"
  - ".git/*"
  - "LICENSE"
  - "Sample/*"
  - "Sample"

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences